# Generated by Django 5.0.6 on 2024-05-16 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_doctor_availability_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='treatment_duration',
            field=models.IntegerField(choices=[(15, '15 minutes'), (30, '30 minutes'), (45, '45 minutes'), (60, '60 minutes')], default=15),
            preserve_default=False,
        ),
    ]
